name: conquest
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  dio: ^5.9.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.3.1
  flutter_secure_storage: ^10.0.0
  flutter_svg: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Vertigo
      fonts:
        - asset: assets/fonts/vertigo.ttf
    - family: Gpkn
      fonts:
        - asset: assets/fonts/gpkn.ttf
    

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo_square.png"
  adaptive_icon_foreground: "assets/images/logo_foreground.png"
  adaptive_icon_background: "#DAF1DE"
