name: conquest
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  camera: ^0.12.0+1
  connectivity_plus: ^7.1.1
  dart_jsonwebtoken: ^3.4.1
  dio: ^5.9.2
  flutter:
    sdk: flutter
  flutter_foreground_task: ^9.2.2
  flutter_map: ^8.3.0
  flutter_riverpod: ^3.3.1
  flutter_secure_storage: ^10.0.0
  flutter_svg: ^2.2.4
  geolocator: ^14.0.2
  health: ^13.3.1
  image: ^4.8.0
  latlong2: ^0.9.1
  path: ^1.9.1
  path_provider: ^2.1.5
  pedometer: ^4.2.0
  permission_handler: ^12.0.1
  shared_preferences: ^2.5.5
  sqflite: ^2.4.2
  tflite_flutter: ^0.12.1
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/images/league/
    - assets/images/character/
    - assets/models/labelmap.txt
    - assets/models/yolov8n.tflite

  fonts:
    - family: Vertigo
      fonts:
        - asset: assets/fonts/vertigo.ttf
    - family: Gpkn
      fonts:
        - asset: assets/fonts/gpkn.ttf
    

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo_square.png"
  adaptive_icon_foreground: "assets/images/logo_foreground.png"
  adaptive_icon_background: "#DAF1DE"
